// Generate the fixed 256-color display palette by farthest-point sampling (FPS)
// in OKLab, restricted to the sRGB gamut.
//
// Why a generated asset (not a closed-form generator): a hard cap of 256 colors
// with the best achievable worst-case perceptual spacing. FPS greedily maximizes
// the minimum pairwise OKLab ΔE, which no closed-form indexed sequence matches —
// the trade is that the result is an unordered *set*, so it must be precomputed
// and stored, and `color_id` is capped at the palette size (see COLOR_ID_MAX).
//
// Determinism: the candidate grid is fixed and the FPS seed is the maximum-chroma
// candidate (stable tie-break), with no RNG — regenerating always yields the same
// palette. Colors are emitted farthest-first, so low ids are the most separated.
//
// Color math: OKLab / OKLCh per B. Ottosson, 2020
// (https://bottosson.github.io/posts/oklab/).
//
// Run:  node scripts/generate-palette.mjs
// Emits: src/lib/palette.ts

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const N = 256;

// Lightness band: mid-range so every swatch reads on light and dark grounds,
// but wide enough to recover gamut volume (better packing than a narrow band).
const L_MIN = 0.45;
const L_MAX = 0.86;
const AB_LIMIT = 0.37; // OKLab a/b extent to scan; sRGB chroma never exceeds this
const STEP = 0.012;

// --- OKLab -> linear sRGB -> sRGB (Ottosson inverse matrices) --------------
function oklabToLinearSrgb(L, a, b) {
  const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = L - 0.0894841775 * a - 1.291485548 * b;
  const l = l_ ** 3, m = m_ ** 3, s = s_ ** 3;
  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];
}
const inGamut = (r, g, b, eps = 1e-4) =>
  r >= -eps && r <= 1 + eps &&
  g >= -eps && g <= 1 + eps &&
  b >= -eps && b <= 1 + eps;

// --- candidate set: every in-gamut grid point in the lightness band --------
const candidates = [];
for (let L = L_MIN; L <= L_MAX + 1e-9; L += STEP) {
  for (let a = -AB_LIMIT; a <= AB_LIMIT + 1e-9; a += STEP) {
    for (let b = -AB_LIMIT; b <= AB_LIMIT + 1e-9; b += STEP) {
      const [r, g, bl] = oklabToLinearSrgb(L, a, b);
      if (inGamut(r, g, bl)) candidates.push({ L, a, b });
    }
  }
}
if (candidates.length < N) {
  throw new Error(`only ${candidates.length} in-gamut candidates for N=${N}`);
}

// --- farthest-point sampling ----------------------------------------------
const d2 = (p, q) => (p.L - q.L) ** 2 + (p.a - q.a) ** 2 + (p.b - q.b) ** 2;

// Deterministic seed: maximum-chroma candidate (tie-break by L, then b).
let seed = 0;
for (let i = 1; i < candidates.length; i++) {
  const c = candidates[i], s = candidates[seed];
  const cc = c.a * c.a + c.b * c.b, sc = s.a * s.a + s.b * s.b;
  if (cc > sc || (cc === sc && (c.L > s.L || (c.L === s.L && c.b > s.b)))) seed = i;
}

const chosen = [candidates[seed]];
const dist = candidates.map((c) => d2(c, candidates[seed]));
for (let k = 1; k < N; k++) {
  let far = 0;
  for (let i = 1; i < candidates.length; i++) if (dist[i] > dist[far]) far = i;
  chosen.push(candidates[far]);
  for (let i = 0; i < candidates.length; i++) {
    const d = d2(candidates[i], candidates[far]);
    if (d < dist[i]) dist[i] = d;
  }
}

// --- report worst-case spacing --------------------------------------------
let minDE = Infinity;
for (let i = 0; i < chosen.length; i++) {
  for (let j = i + 1; j < chosen.length; j++) {
    const d = Math.sqrt(d2(chosen[i], chosen[j]));
    if (d < minDE) minDE = d;
  }
}

// --- emit OKLCh strings -----------------------------------------------------
const toOklch = ({ L, a, b }) => {
  const C = Math.hypot(a, b);
  let h = (Math.atan2(b, a) * 180) / Math.PI;
  if (h < 0) h += 360;
  return `oklch(${L.toFixed(4)} ${C.toFixed(4)} ${h.toFixed(2)})`;
};

const lines = chosen.map((c) => `  "${toOklch(c)}",`).join("\n");
const out = `// AUTO-GENERATED by scripts/generate-palette.mjs — do not edit by hand.
//
// ${N} display colors, farthest-point sampled in OKLab within the sRGB gamut
// (B. Ottosson, 2020), ordered farthest-first so low ids are the most spread.
// Worst-case pair ΔE(OKLab) = ${minDE.toFixed(4)} over ${candidates.length} candidates.
// Regenerate: node scripts/generate-palette.mjs

export const PALETTE: readonly string[] = [
${lines}
];
`;

const here = dirname(fileURLToPath(import.meta.url));
const target = resolve(here, "..", "src", "lib", "palette.ts");
writeFileSync(target, out, "utf8");
console.log(
  `wrote ${target}\n  ${N} colors from ${candidates.length} candidates` +
  `\n  worst-case OKLab ΔE = ${minDE.toFixed(4)}`,
);
